#!/bin/bash
### ---
### name: 'NF_GWAS:SINGLE_VARIANT_TESTS:REGENIE:REGENIE_STEP2:REGENIE_STEP2_RUN (1000g_lpa_hg38)'
### container: 'quay.io/genepi/nf-gwas:v1.0.8'
### outputs:
### - '*regenie.gz'
### - '*regenie.Ydict'
### - '1000g_lpa_hg38.vcf*.log'
### ...
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}

nxf_container_env() {
cat << EOF
export PATH="\$PATH:/home/ec2-user/GWAS/nf-gwas/scripts/gwas_nf/Nextflow_Scripts/bin"
EOF
}

nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  rsync -rRl $1 $2
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf -- $exit_status > /home/ec2-user/GWAS/nf-gwas/scripts/gwas_nf/Nextflow_Scripts/work/b3/dd1cbbc8e8f3b2a933aa918d7662ed/.exitcode
    set +u
    docker rm $NXF_BOXID &>/dev/null || true
    exit $exit_status
}

on_term() {
    set +e
    docker stop $NXF_BOXID
}

nxf_launch() {
    docker run -i --cpu-shares 8192 --memory 8192m -e "NXF_TASK_WORKDIR" -v /home/ec2-user/GWAS/nf-gwas/scripts/gwas_nf/Nextflow_Scripts:/home/ec2-user/GWAS/nf-gwas/scripts/gwas_nf/Nextflow_Scripts -w "$NXF_TASK_WORKDIR" --name $NXF_BOXID quay.io/genepi/nf-gwas:v1.0.8 /bin/bash -c "eval $(nxf_container_env); /bin/bash -ue /home/ec2-user/GWAS/nf-gwas/scripts/gwas_nf/Nextflow_Scripts/work/b3/dd1cbbc8e8f3b2a933aa918d7662ed/.command.sh"
}

nxf_stage() {
    true
    # stage input files
    rm -f phenotype.validated.txt
    rm -f regenie_step1_out.log
    rm -f regenie_step1_out_pred.list
    rm -f 1000g_lpa_hg38.vcf.pgen
    rm -f regenie_step1_out_2.loco.gz
    rm -f 1000g_lpa_hg38.vcf.psam
    rm -f regenie_step1_out_1.loco.gz
    rm -f 1000g_lpa_hg38.vcf.pvar
    ln -s /home/ec2-user/GWAS/nf-gwas/scripts/gwas_nf/Nextflow_Scripts/work/6d/4120c47109d2c1024f6562ecc217dd/phenotype.validated.txt phenotype.validated.txt
    ln -s /home/ec2-user/GWAS/nf-gwas/scripts/gwas_nf/Nextflow_Scripts/work/67/d751d1d420254d96c1186a8c766a62/regenie_step1_out.log regenie_step1_out.log
    ln -s /home/ec2-user/GWAS/nf-gwas/scripts/gwas_nf/Nextflow_Scripts/work/67/d751d1d420254d96c1186a8c766a62/regenie_step1_out_pred.list regenie_step1_out_pred.list
    ln -s /home/ec2-user/GWAS/nf-gwas/scripts/gwas_nf/Nextflow_Scripts/work/c9/fc42ab719eadd60d1392f8e2d1eba2/1000g_lpa_hg38.vcf.pgen 1000g_lpa_hg38.vcf.pgen
    ln -s /home/ec2-user/GWAS/nf-gwas/scripts/gwas_nf/Nextflow_Scripts/work/67/d751d1d420254d96c1186a8c766a62/regenie_step1_out_2.loco.gz regenie_step1_out_2.loco.gz
    ln -s /home/ec2-user/GWAS/nf-gwas/scripts/gwas_nf/Nextflow_Scripts/work/c9/fc42ab719eadd60d1392f8e2d1eba2/1000g_lpa_hg38.vcf.psam 1000g_lpa_hg38.vcf.psam
    ln -s /home/ec2-user/GWAS/nf-gwas/scripts/gwas_nf/Nextflow_Scripts/work/67/d751d1d420254d96c1186a8c766a62/regenie_step1_out_1.loco.gz regenie_step1_out_1.loco.gz
    ln -s /home/ec2-user/GWAS/nf-gwas/scripts/gwas_nf/Nextflow_Scripts/work/c9/fc42ab719eadd60d1392f8e2d1eba2/1000g_lpa_hg38.vcf.pvar 1000g_lpa_hg38.vcf.pvar
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    export NXF_BOXID="nxf-$(dd bs=18 count=1 if=/dev/urandom 2>/dev/null | base64 | tr +/ 0A | tr -d '\r\n')"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /home/ec2-user/GWAS/nf-gwas/scripts/gwas_nf/Nextflow_Scripts/work/b3/dd1cbbc8e8f3b2a933aa918d7662ed/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    export NXF_TASK_WORKDIR="$PWD"
    nxf_stage

    set +e
    (set -o pipefail; (nxf_launch | tee .command.out) 3>&1 1>&2 2>&3 | tee .command.err) &
    pid=$!
    wait $pid || nxf_main_ret=$?
    nxf_unstage
}

$NXF_ENTRY
